name: wpm

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: log in
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: log in to acr
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: get current date
        run: echo "DATE_TIME=$(date +'%d%m%Y')" >> $GITHUB_ENV

      - name: build management container image
        run: docker build Wpm.Management.Api -f ./Wpm.Management.Api/Dockerfile -t ${{ secrets.ACR_LOGIN_SERVER }}/wpm-management-api:${{ env.DATE_TIME }}.${{ github.run_number}}

      - name: push management container image
        run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/wpm-management-api:${{ env.DATE_TIME }}.${{ github.run_number}}

      - name: deploy management to container apps
        uses: azure/container-apps-deploy-action@v2
        with:
          acrName: ${{ secrets.ACR_USERNAME }}
          acrUsername: ${{ secrets.ACR_USERNAME }}
          acrPassword: ${{ secrets.ACR_PASSWORD }}
          containerAppName: wpm-management
          resourceGroup: wpm
          imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/wpm-management-api:${{ env.DATE_TIME }}.${{ github.run_number}}
          environmentVariables: Logging__LogLevel__Microsoft.EntityFrameworkCore=Debug

      - name: build clinic container image
        run: docker build Wpm.Clinic.Api -f ./Wpm.Clinic.Api/Dockerfile -t ${{ secrets.ACR_LOGIN_SERVER }}/wpm-clinic-api:${{ env.DATE_TIME }}.${{ github.run_number}}
  
      - name: push clinic container image
        run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/wpm-clinic-api:${{ env.DATE_TIME }}.${{ github.run_number}}
  
      - name: deploy clinic to container apps
        uses: azure/container-apps-deploy-action@v2
        with:
          acrName: ${{ secrets.ACR_USERNAME }}
          acrUsername: ${{ secrets.ACR_USERNAME }}
          acrPassword: ${{ secrets.ACR_PASSWORD }}
          containerAppName: wpm-clinic
          resourceGroup: wpm
          imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/wpm-clinic-api:${{ env.DATE_TIME }}.${{ github.run_number}}
          environmentVariables: Logging__LogLevel__Microsoft.EntityFrameworkCore=Debug Wpm__ManagementServiceUri=http://wpm-management
